import {useState} from 'react';
import {Alert,Image,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import {router} from 'expo-router';
import {Pet} from '@/types';
import {updatePetPhoto,upsertPet} from '@/data/pets';
import {hasPawPassPlus} from '@/data/subscriptions';
import {PickedPetPhoto,uploadPetPhoto,validatePetPhoto} from '@/data/petPhotos';
import {colors,radius} from '@/theme';

const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n));

export function PetForm({initial}:{initial?:Pet}){
  const[name,setName]=useState(initial?.name??'');const[species,setSpecies]=useState(initial?.species??'dog');const[breed,setBreed]=useState(initial?.breed??'');const[age,setAge]=useState(initial?.age??'');const[weight,setWeight]=useState(initial?.weight??'');const[sex,setSex]=useState(initial?.sex??'Unknown');const[microchip,setMicrochip]=useState(initial?.microchip??'');const[allergies,setAllergies]=useState(initial?.allergies??'');const[medications,setMedications]=useState(initial?.medications??'');const[vetName,setVetName]=useState(initial?.vet_name??'');
  const[saving,setSaving]=useState(false);const[picked,setPicked]=useState<PickedPetPhoto|null>(null);const[frameX,setFrameX]=useState(initial?.photo_position_x??50);const[frameY,setFrameY]=useState(initial?.photo_position_y??50);const[zoom,setZoom]=useState(initial?.photo_zoom??1);
  const preview=picked?.uri||initial?.photo_url||'';
  const pickPhoto=async()=>{try{if(!(await hasPawPassPlus())){Alert.alert('PawPass Plus','Pet profile photos are a PawPass Plus feature. Upgrade in Settings to personalize your pet profile.');return;}const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Photo access needed','Allow PawPass to access your photos so you can choose a pet profile picture.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.9,allowsEditing:false});if(result.canceled)return;const asset=result.assets[0];const photo:PickedPetPhoto={uri:asset.uri,fileName:asset.fileName,mimeType:asset.mimeType,fileSize:asset.fileSize};validatePetPhoto(photo);setPicked(photo);setFrameX(50);setFrameY(50);setZoom(1);}catch(e){Alert.alert('Could not choose photo',e instanceof Error?e.message:'Please try again.')}};
  const save=async()=>{if(!name.trim()||!breed.trim()||!weight.trim())return Alert.alert('Missing details','Name, breed, and weight are required.');setSaving(true);try{let pet=await upsertPet({...initial,name,species,breed,age,weight,sex,microchip,allergies,medications,vet_name:vetName,photo_position_x:frameX,photo_position_y:frameY,photo_zoom:zoom});if(picked){const url=await uploadPetPhoto(pet.id,picked);pet=await updatePetPhoto(pet.id,url,frameX,frameY,zoom);}router.replace(`/pet/${pet.id}`)}catch(e){Alert.alert('Could not save pet',e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}};
  const input=(label:string,value:string,setter:(v:string)=>void,placeholder?:string)=><View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={setter} placeholder={placeholder} placeholderTextColor="#97A29E"/></View>;
  const move=(dx:number,dy:number)=>{setFrameX(x=>clamp(x+dx,0,100));setFrameY(y=>clamp(y+dy,0,100));};
  const transform=[{scale:Math.max(1,Number(zoom))},{translateX:(50-frameX)*.35},{translateY:(50-frameY)*.35}];
  return <View style={{gap:14}}>
    <View style={styles.photoSection}><View style={styles.photoPreview}>{preview?<Image source={{uri:preview}} style={[styles.photo,{transform}]} resizeMode="cover"/>:<Text style={styles.emoji}>{initial?.animal||'🐾'}</Text>}</View><View style={{flex:1,gap:8}}><View style={styles.plusRow}><Text style={styles.label}>Profile photo</Text><Text style={styles.plusBadge}>PawPass Plus</Text></View><Pressable style={styles.photoButton} onPress={pickPhoto}><Text style={styles.photoButtonText}>{preview?'Choose another photo':'Choose photo'}</Text></Pressable></View></View>
    {preview?<View style={styles.frameCard}><Text style={styles.frameTitle}>Frame your pet</Text><Text style={styles.frameHelp}>Use the controls to center your pet. The original uploaded photo stays unchanged.</Text><View style={styles.controlRow}><Pressable style={styles.control} onPress={()=>move(0,-5)}><Text>↑</Text></Pressable><Pressable style={styles.control} onPress={()=>move(-5,0)}><Text>←</Text></Pressable><Pressable style={styles.control} onPress={()=>move(5,0)}><Text>→</Text></Pressable><Pressable style={styles.control} onPress={()=>move(0,5)}><Text>↓</Text></Pressable><Pressable style={styles.control} onPress={()=>setZoom(z=>clamp(Number((z-.1).toFixed(2)),1,3))}><Text>−</Text></Pressable><Text style={styles.zoomText}>{zoom.toFixed(1)}×</Text><Pressable style={styles.control} onPress={()=>setZoom(z=>clamp(Number((z+.1).toFixed(2)),1,3))}><Text>+</Text></Pressable></View></View>:null}
    {input('Pet name',name,setName,'Milo')}{input('Species',species,setSpecies,'dog, cat, bird')}{input('Breed',breed,setBreed,'Golden Retriever')}{input('Age',age,setAge,'3 years')}{input('Weight',weight,setWeight,'31 kg')}{input('Sex',sex,setSex,'Male / Female / Unknown')}{input('Microchip',microchip,setMicrochip)}{input('Allergies',allergies,setAllergies,'None known')}{input('Medications',medications,setMedications,'None')}{input('Veterinarian',vetName,setVetName)}<Pressable style={styles.button} disabled={saving} onPress={save}><Text style={styles.buttonText}>{saving?'Saving…':'Save pet'}</Text></Pressable></View>}

const styles=StyleSheet.create({field:{gap:7},label:{fontWeight:'800',color:colors.ink,fontSize:12},input:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,paddingHorizontal:14,paddingVertical:13,color:colors.ink},button:{backgroundColor:colors.coral,borderRadius:radius.md,padding:16,alignItems:'center',marginTop:6},buttonText:{color:colors.ink,fontWeight:'900',fontSize:16},photoSection:{flexDirection:'row',gap:12,alignItems:'center'},photoPreview:{width:88,height:88,borderRadius:22,overflow:'hidden',backgroundColor:colors.mintLight,alignItems:'center',justifyContent:'center'},photo:{width:'100%',height:'100%'},emoji:{fontSize:46},plusRow:{flexDirection:'row',alignItems:'center',gap:7,flexWrap:'wrap'},plusBadge:{fontSize:10,fontWeight:'900',backgroundColor:colors.coralLight,color:colors.ink,paddingHorizontal:8,paddingVertical:4,borderRadius:999},photoButton:{borderWidth:1,borderColor:colors.line,borderRadius:radius.md,paddingVertical:11,paddingHorizontal:12,alignItems:'center'},photoButtonText:{fontWeight:'900',color:colors.ink},frameCard:{backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,padding:12,gap:8},frameTitle:{fontWeight:'900',color:colors.ink},frameHelp:{fontSize:11,color:colors.muted,lineHeight:16},controlRow:{flexDirection:'row',alignItems:'center',gap:7,flexWrap:'wrap'},control:{minWidth:36,minHeight:36,borderRadius:10,backgroundColor:colors.mintLight,alignItems:'center',justifyContent:'center'},zoomText:{fontWeight:'900',color:colors.ink,minWidth:38,textAlign:'center'}});
